apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster
  region: ap-southeast-1

privateCluster:
  enabled: true             # A fully-private cluster does not support modifying clusterEndpointAccess during cluster creation. 
                            # After the cluster and worker node group creation. eksctl will update cluster network mode from public + private to private.

vpc:
  id: <Your VPC ID>
  subnets:
    private:
      ap-southeast-1a:
        id: <Your Subnet>
      ap-southeast-1b:
        id: <Your Subnet>
      ap-southeast-1c:
        id: <Your Subnet>

managedNodeGroups:
  - name: node-group
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 5
    privateNetworking: true