apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: public-cluster
  region: ap-southeast-1

vpc:
  id: <Your VPC ID>
  subnets:
    public:
      ap-southeast-1a:
        id: <Your Subnet>
      ap-southeast-1b:
        id: <Your Subnet>
      ap-southeast-1c:
        id: <Your Subnet>

managedNodeGroups:
  - name: node-group
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 5