apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: public-private-cluster
  region: ap-southeast-1

vpc:
  nat:
    gateway: Single # other options: Disable, Single (default), HighlyAvailable
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  id: <Your VPC ID>
  subnets:
    private:
      ap-southeast-1a:
        id: <Your Subnet>
      ap-southeast-1b:
        id: <Your Subnet>
      ap-southeast-1c:
        id: <Your Subnet>

managedNodeGroups:
  - name: node-group
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 5
    privateNetworking: true