apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: public-private-cluster-auto-vpc
  region: ap-southeast-1

vpc:
  cidr: 10.10.0.0/16
  nat:
    gateway: Single # other options: Disable, Single (default), HighlyAvailable
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  

managedNodeGroups:
  - name: node-group
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 5
    privateNetworking: true